vim.cmd.set("expandtab")
vim.cmd.set("tabstop=4")
vim.cmd.set("softtabstop=4")
vim.cmd.set("shiftwidth=4")
vim.cmd.set("termguicolors")
vim.cmd.set("nu")
vim.cmd.set("relativenumber")
vim.keymap.set('n', '<leader>pe', vim.cmd.Ex, {})
